# ---------------------------
# CLOUD BUILD PIPELINE
# Deploys:
# 1) .NET Core API  (ragserver-api)
# 2) Angular App    (ragserver-app)
# ---------------------------

steps:

  # ================================
  # 1) BUILD & PUSH .NET API IMAGE
  # ================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', '${_LOCATION}/${PROJECT_ID}/${_API_IMAGE}',
        './RAGServer.API'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '${_LOCATION}/${PROJECT_ID}/${_API_IMAGE}'
      ]

  # Deploy API to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run','deploy','ragserver-api',
        '--image','${_LOCATION}/${PROJECT_ID}/${_API_IMAGE}',
        '--region','${_REGION}',
        '--platform','managed',
        '--allow-unauthenticated',
        '--port','8080',
        '--timeout','300',
        '--add-cloudsql-instances','rag-server-480413:asia-south1:rag-server-db-instance'
      ]


  # ================================
  # 2) BUILD & PUSH ANGULAR APP IMAGE
  # ================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', '${_LOCATION}/${PROJECT_ID}/${_APP_IMAGE}',
        './RAGServer.APP'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '${_LOCATION}/${PROJECT_ID}/${_APP_IMAGE}'
      ]

  # Deploy Angular App to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run','deploy','ragserver-app',
        '--image','${_LOCATION}/${PROJECT_ID}/${_APP_IMAGE}',
        '--region','${_REGION}',
        '--platform','managed',
        '--allow-unauthenticated',
        '--port','8080',
        '--timeout','300'
      ]


# ==================================================
# Images shown in Cloud Build UI
# ==================================================
images:
  - ${_LOCATION}/${PROJECT_ID}/${_API_IMAGE}
  - ${_LOCATION}/${PROJECT_ID}/${_APP_IMAGE}

# ==================================================
# SUBSTITUTIONS (CUSTOM VARIABLES)
# ==================================================
substitutions:
  _REGION: asia-south1
  _LOCATION: asia-south1-docker.pkg.dev

  # Artifact Registry paths
  _API_IMAGE: ragserver-api-repo/ragserver-api:latest
  _APP_IMAGE: ragserver-app-repo/ragserver-app:latest

options:
  logging: CLOUD_LOGGING_ONLY
